@startuml 集計1

!include ./style.inc

hide footbox

actor user
participant node as "node.js"
participant js as "集計ツール\naggregation.js"
participant excel as "試験項目書.xlsx"
participant json as "集計結果.json"

user -> node : node aggregation.js\n -i 試験項目書.xlsx\n -o 集計結果.json
activate node
    node -> js : 読み込み
    node <-- js
    node -> excel : 読み込み
    node <-- excel
    node -> node : 解析 / 集計
    node -> json : 出力
deactivate node

@enduml