# page title
title: "製品一覧"
# url path.
path: /products
# スクリーンショット path。ない場合は空欄
image: /products.drawio.png
# 複数枚ある場合は、imagesを利用
# images:
#   - xxx
#   - yyy

# 説明
description: |-
  {説明文}
# label text, to url を配列形式で記載
links:
  - label: "製品追加"
    to: /products/add
  - label: "製品詳細"
    to: /products/{product_id}/view
  - label: "製品編集"
    to: /products/{product_id}/edit
  - label: "製品削除"
    to: /products/{product_id}/remove

# sitemap での深さを指定する時に利用
# depth: 0
# sitemap での上の要素からの相対位置を指定する時に利用
span: 3